"""posts update

Revision ID: 909097529059
Revises: f987729f94ca
Create Date: 2020-05-11 12:35:09.449443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909097529059'
down_revision = 'f987729f94ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'author')
    # ### end Alembic commands ###
