"""create table

Revision ID: b56ce8e9a393
Revises: 909097529059
Create Date: 2020-05-11 13:25:13.517377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b56ce8e9a393'
down_revision = '909097529059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.String(length=100), nullable=False))
    op.drop_column('post', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('post', 'title')
    # ### end Alembic commands ###
